/**
 * Creating a sidebar enables you to:
 create an ordered group of docs
 render a sidebar for each doc of that group
 provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // learningLab: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'learningLab',
  //   },
  // ],

  // ecosystem: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'Ecosystem',
  //   },
  // ],

  docs: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      items: [
        'overview/intro',
        'overview/what-is-lit',
        'overview/how-lit-works',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      items: [
        'getting-started/installing-the-sdk',
        {
          type: 'category',
          label: 'Connecting to a Lit Network',
          link: {
            type: 'doc',
            id: 'getting-started/connecting-to-lit/connecting-to-lit',
          },
          items: [
            'getting-started/connecting-to-lit/mainnets',
            'getting-started/connecting-to-lit/testnets',
          ],
        },
        'getting-started/next-steps',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'tutorials/overview',
      },
      items: [
        'tutorials/encrypting-file',
        'tutorials/off-chain-data',
        'tutorials/pkp-sign-tx',
        {
          type: 'category',
          label: 'Advanced',
          items: ['tutorials/advanced/custom-auth-telegram'],
        },
      ],
    },
    {
      type: 'category',
      label: 'How To Guides',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Capacity Credits',
          items: [
            {
              type: 'category',
              label: 'Minting a Credit',
              collapsible: false,
              items: [
                'how-to-guides/capacity-credits/minting/using-contracts-sdk',
                'how-to-guides/capacity-credits/minting/using-lit-explorer',
              ],
            },
            'how-to-guides/capacity-credits/delegating-a-credit',
            'how-to-guides/capacity-credits/using-delegated-credit',
          ],
        },
        {
          type: 'category',
          label: 'Session Signatures',
          items: [
            {
              type: 'category',
              label: 'Generating Session Sigs',
              collapsible: false,
              items: [
                'how-to-guides/session-sigs/generate/using-auth-sig',
                'how-to-guides/session-sigs/generate/using-pkp',
                'how-to-guides/session-sigs/generate/using-lit-action',
              ],
            },
            'how-to-guides/session-sigs/authenticating',
          ],
        },
        {
          type: 'category',
          label: 'Programmable Key Pairs (PKPs)',
          items: [
            {
              type: 'category',
              label: 'Minting',
              items: [
                'how-to-guides/pkps/minting/using-contracts-sdk',
                'how-to-guides/pkps/minting/using-lit-explorer',
                'how-to-guides/pkps/minting/using-discord-oauth',
                'how-to-guides/pkps/minting/using-google-oauth',
                'how-to-guides/pkps/minting/using-stytch',
                'how-to-guides/pkps/minting/using-web-authn',
                'how-to-guides/pkps/minting/using-custom-auth-method',
                'how-to-guides/pkps/minting/with-multiple-auth-methods',
              ],
            },
            {
              type: 'category',
              label: 'Connect to a dApp',
              items: [
                'how-to-guides/pkps/connecting/using-pkp-ethers-wallet',
                'how-to-guides/pkps/connecting/using-wallet-connect',
              ],
            },
            {
              type: 'category',
              label: 'Manage Permitted Auth Methods',
              items: [
                'how-to-guides/pkps/manage-auth-methods/add-auth-method',
                'how-to-guides/pkps/manage-auth-methods/add-custom-auth-method',
                'how-to-guides/pkps/manage-auth-methods/remove-auth-method',
              ],
            },
            {
              type: 'category',
              label: 'Deterministically Derive Keys',
              items: [
                'how-to-guides/pkps/derive-keys/using-discord-oauth',
                'how-to-guides/pkps/derive-keys/using-google-oauth',
                'how-to-guides/pkps/derive-keys/using-stytch',
                'how-to-guides/pkps/derive-keys/using-lit-action',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Wrapped Keys',
          items: [
            'how-to-guides/wrapped-keys/generate',
            'how-to-guides/wrapped-keys/import',
            'how-to-guides/wrapped-keys/export',
            'how-to-guides/wrapped-keys/get-metadata',
            'how-to-guides/wrapped-keys/store-metadata',
            'how-to-guides/wrapped-keys/list-keys-for-pkp',
            'how-to-guides/wrapped-keys/sign-msg',
            'how-to-guides/wrapped-keys/sign-tx',
            'how-to-guides/wrapped-keys/custom-wrapped-key',
          ],
        },
        {
          type: 'category',
          label: 'Encrypt with Lit',
          items: [
            'how-to-guides/encryption/encrypt-string',
            'how-to-guides/encryption/zip-encrypt-string',
            'how-to-guides/encryption/encrypt-file',
            'how-to-guides/encryption/zip-encrypt-file',
            'how-to-guides/encryption/zip-encrypt-files',
            'how-to-guides/encryption/encrypt-to-json',
          ],
        },
        {
          type: 'category',
          label: 'Access Control',
          items: [
            'how-to-guides/access-control/jwt-auth',
            {
              type: 'category',
              label: 'Combine Control Conditions',
              items: [
                'how-to-guides/access-control/combining/unified-accs',
                'how-to-guides/access-control/combining/boolean-logic',
              ],
            },
            {
              type: 'category',
              label: 'EVM Based Control Conditions',
              items: [
                'how-to-guides/access-control/evm/custom-contract-calls',
                {
                  type: 'category',
                  label: 'ERC-1155',
                  items: [
                    'how-to-guides/access-control/evm/erc1155/possess-token-with-id',
                    'how-to-guides/access-control/evm/erc1155/possess-token-with-ids',
                  ],
                },
                {
                  type: 'category',
                  label: 'ERC-721',
                  items: [
                    'how-to-guides/access-control/evm/erc721/possess-token-with-id',
                    'how-to-guides/access-control/evm/erc721/possess-token-in-collection',
                  ],
                },
                {
                  type: 'category',
                  label: 'Sign in with Ethereum (SIWE)',
                  items: [
                    'how-to-guides/access-control/evm/siwe/specific-domain',
                    'how-to-guides/access-control/evm/siwe/specific-resources',
                  ],
                },
                {
                  type: 'category',
                  label: 'POAP',
                  items: [
                    'how-to-guides/access-control/evm/poap/possess-poap-specific-name',
                    'how-to-guides/access-control/evm/poap/possess-poap-specific-event-id',
                  ],
                },
                'how-to-guides/access-control/evm/erc20-possess-token',
                'how-to-guides/access-control/evm/possess-eth',
                'how-to-guides/access-control/evm/specific-address',
                'how-to-guides/access-control/evm/time-based',
                'how-to-guides/access-control/evm/dao-member',
                'how-to-guides/access-control/evm/proof-of-humanity',
              ],
            },
            {
              type: 'category',
              label: 'Solana Based Control Conditions',
              items: [
                'how-to-guides/access-control/solana/possess-sol',
                'how-to-guides/access-control/solana/specific-address',
                'how-to-guides/access-control/solana/possess-token',
                'how-to-guides/access-control/solana/specific-token-account-balance',
                'how-to-guides/access-control/solana/program-derived-address',
              ],
            },
            'how-to-guides/access-control/lit-action',
          ],
        },
        {
          type: 'category',
          label: 'Lit Actions (Decentralized Compute)',
          items: [
            'how-to-guides/lit-actions/using-dependencies',
            'how-to-guides/lit-actions/conditional-signing',
            'how-to-guides/lit-actions/http-requests',
            'how-to-guides/lit-actions/decryption',
            'how-to-guides/lit-actions/sign-msg',
            'how-to-guides/lit-actions/sign-eth-tx',
            'how-to-guides/lit-actions/eip-191-signing',
            'how-to-guides/lit-actions/run-on-single-node',
            'how-to-guides/lit-actions/get-rpc-urls',
            'how-to-guides/lit-actions/broadcast-and-collect',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Topic Guides',
      items: [
        'topic-guides/access-control-conditions',
        'topic-guides/auth-methods',
        'topic-guides/auth-sigs',
        'topic-guides/capacity-credits',
        'topic-guides/claimable-keys',
        'topic-guides/lit-ability',
        'topic-guides/lit-action',
        {
          type: 'category',
          label: 'Lit Blockchains',
          items: [
            'topic-guides/chronicle-yellowstone',
            'topic-guides/chronicle',
          ],
        },
        'topic-guides/lit-encryption-metadata',
        'topic-guides/lit-relayer',
        'topic-guides/lit-resource',
        'topic-guides/paying-for-lit',
        'topic-guides/payment-delegation-db',
        'topic-guides/pkps',
        'topic-guides/session-capability-object',
        'topic-guides/session-sigs',
        'topic-guides/wrapped-keys',
        'topic-guides/unified-access-control-conditions',
      ],
    },
    {
      type: 'category',
      label: 'Reference Guides',
      collapsible: false,
      items: [
        'reference-guides/paying-for-lit',
        'reference-guides/pkps-vs-wrapped-keys',
        'reference-guides/deploying-lit-action',
        {
          type: 'category',
          label: 'Migrating Lit Networks',
          items: ['reference-guides/migrating-network/to-datil'],
        },
        {
          type: 'category',
          label: 'Migrating Lit SDK Versions',
          items: ['reference-guides/migrating-sdk/v5-to-v6'],
        },
      ],
    },
  ],
};

module.exports = sidebars;
