/**
 * Creating a sidebar enables you to:
 create an ordered group of docs
 render a sidebar for each doc of that group
 provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // learningLab: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'learningLab',
  //   },
  // ],

  // ecosystem: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'Ecosystem',
  //   },
  // ],

  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      className: "category-not-collapsible",
      items: [
        "intro/overview",
        "intro/what-is-lit-protocol",
        "intro/rollup",
        "intro/usecases",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsible: false,
      className: "category-not-collapsible",
      items: ["concepts/pkps-as-wallet"],
    },
    {
      type: "category",
      label: "Access Control",
      collapsible: true,
      items: [
        "access-control/intro",
        "access-control/encryption",
        "access-control/jwt-auth",
        {
          type: "category",
          label: "Types of Conditions",
          collapsed: true,
          items: [
            "access-control/condition-types/unified-access-control-conditions",
            "access-control/condition-types/boolean-logic",
            "access-control/condition-types/lit-action-conditions",
          ],
        },
        {
          type: "category",
          label: "EVM",
          collapsed: true,
          items: [
            "access-control/evm/basic-examples",
            "access-control/evm/custom-contract-calls",
            "access-control/evm/poap",
            "access-control/evm/timelock",
            "access-control/evm/siwe",
          ],
        },
        {
          type: "category",
          label: "Other Chains",
          collapsed: true,
          items: [
            "access-control/other-chains/sol-rpc-conditions",
            "access-control/other-chains/cosmos-conditions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Programmable Key Pairs",
      collapsible: true,
      items: [
        "pkp/intro",
        "pkp/minting",
        "pkp/auth-methods",
        "pkp/pkps-and-actions",
        "pkp/usage",
        "pkp/walletconnect",
        "pkp/tools-and-examples",
      ],
    },
    {
      type: "category",
      label: "Lit Actions",
      collapsible: true,
      items: [
        "lit-actions/intro",
        "lit-actions/getlit-cli",
        "lit-actions/hello-world",
        "lit-actions/best-practices",
        {
          type: "category",
          label: "Working With Lit Actions",
          collapsed: true,
          items: [
            "lit-actions/working-with-actions/conditional-signing",
            "lit-actions/working-with-actions/using-fetch",
            "lit-actions/working-with-actions/single-execution",
            "lit-actions/working-with-actions/signing-tx",
            "lit-actions/working-with-actions/permissions",
            "lit-actions/working-with-actions/log-and-return",
          ],
        },
        {
          type: "category",
          label: "More Examples",
          collapsed: true,
          items: [
            "lit-actions/additional-examples/generating-session-key",
            "lit-actions/additional-examples/using-eip",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SDK Reference",
      collapsible: false,
      className: "category-not-collapsible",
      items: [
        "sdk/intro",
        "sdk/feature-matrix",
        "sdk/explanation/installation",
        "sdk/explanation/migration",
        {
          type: "category",
          label: "Working with the SDK",
          collapsed: true,
          items: [
            "sdk/explanation/encryption",
            "sdk/explanation/jwt-auth",
            {
              type: "category",
              label: "Authentication",
              link: {
                type: "doc",
                id: "sdk/explanation/authentication/overview",
              },
              collapsed: true,
              items: [
                "sdk/explanation/authentication/auth-sig",
                {
                  type: "category",
                  label: "Session Signatures",
                  link: {
                    type: "doc",
                    id: "sdk/explanation/authentication/session-sigs/intro",
                  },
                  collapsed: true,
                  items: [
                    "sdk/explanation/authentication/session-sigs/resources-and-abilities",
                    "sdk/explanation/authentication/session-sigs/capability-objects",
                    "sdk/explanation/authentication/session-sigs/get-session-sigs",
                    "sdk/explanation/authentication/session-sigs/usage",
                    {
                      type: "category",
                      label: "Walletless Signatures",
                      link: {
                        type: "doc",
                        id: "sdk/explanation/authentication/session-sigs/auth-methods/overview",
                      },
                      collapsed: true,
                      items: [
                        "sdk/explanation/authentication/session-sigs/auth-methods/add-remove-auth-methods",
                        "sdk/explanation/authentication/session-sigs/auth-methods/social-login",
                        "sdk/explanation/authentication/session-sigs/auth-methods/web-authn",
                        "sdk/explanation/authentication/session-sigs/auth-methods/email-sms",
                      ],
                    },
                  ],
                },
                "sdk/explanation/authentication/security",
              ],
            },
            "sdk/explanation/tests",
          ],
        },
        {
          type: "category",
          label: "Tools & Integrations",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Tools",
              collapsed: true,
              items: [
                "tools-and-examples/tools/access-control",
                "tools-and-examples/tools/share-modal",
                "tools-and-examples/tools/pkpexplorer",
              ],
            },
            {
              type: "category",
              label: "Integrations",
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "Ceramic Integration",
                  collapsed: true,
                  items: [
                    "tools-and-examples/integrations/ceramic/intro",
                    "tools-and-examples/integrations/ceramic/installation",
                  ],
                },
                "tools-and-examples/integrations/bundlrxarweave",
                "tools-and-examples/integrations/additional-integrations",
              ],
            },
            {
              type: "category",
              label: "Additional Examples",
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "Encrypting and Decrypting On-chain Metadata",
                  collapsed: true,
                  items: [
                    "tools-and-examples/sdk-examples/onchain-metadata/introduction",
                    "tools-and-examples/sdk-examples/onchain-metadata/setup",
                    "tools-and-examples/sdk-examples/onchain-metadata/encrypt-decrypt",
                    "tools-and-examples/sdk-examples/onchain-metadata/smart-contract",
                    "tools-and-examples/sdk-examples/onchain-metadata/frontend",
                    "tools-and-examples/sdk-examples/onchain-metadata/polygon-mumbai",
                  ],
                },
              ],
            },
          ],
        },
        "sdk/examples",
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      className: "category-not-collapsible",
      items: [
        "resources/how-it-works",
        "resources/supported-chains",
        "resources/contracts",
        "resources/glossary",
      ],
    },
    {
      type: "category",
      label: "Support",
      collapsible: false,
      className: "category-not-collapsible",
      items: ["support/faq", "support/bug-bounty", "support/state-of-network"],
    },
  ],
};

module.exports = sidebars;
